package com.quikko.controller;

import com.quikko.model.dto.CapsuleClaimResponse;
import com.quikko.service.CapsuleService;
import jakarta.validation.constraints.Pattern;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

/**
 * REST retrieval endpoint for the /capsule claim page. Leaving a capsule
 * happens over the WebSocket connection at the end of a chat (see
 * {@code com.quikko.websocket.CapsuleWsController}) since that's when the
 * pairing context is still known; claiming happens independently, any time
 * after, via this REST endpoint and the token the user was given.
 */
@RestController
@Validated
public class CapsuleController {

    // Mirrors the shape of tokens actually generated by CapsuleService
    // (Base64 URL-safe, no padding, over 18 random bytes -> 24 chars), with
    // a little slack either side. Malformed tokens are rejected with a 400
    // before ever reaching the repository lookup.
    private static final String TOKEN_PATTERN = "^[A-Za-z0-9_-]{16,64}$";

    private final CapsuleService capsuleService;

    public CapsuleController(CapsuleService capsuleService) {
        this.capsuleService = capsuleService;
    }

    @GetMapping("/api/capsules/claim")
    public CapsuleClaimResponse claim(
            @RequestParam
            @Pattern(regexp = TOKEN_PATTERN, message = "Invalid capsule token format")
            String token) {
        return capsuleService.claim(token);
    }
}
